In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import fetch_openml

In [3]:
mnist = fetch_openml('mnist_784', as_frame=False)

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [4]:
X_train, y_train = mnist.data, mnist.target

In [5]:
X_train.shape

(70000, 784)

In [6]:
y_train.shape

(70000,)

<h2>Multiclass Classification</h2>

In [7]:
from sklearn.svm import SVC

In [8]:
svm_clf = SVC(random_state=42)

In [9]:
svm_clf.fit(X_train[:2000], y_train[:2000])

SVC(random_state=42)

In [10]:
test_digit = X_train[45]

In [11]:
svm_clf.predict([test_digit])

array(['9'], dtype=object)

In [12]:
y_train[45] # Indeed we got the Correct Answer

'9'

In [13]:
scores = svm_clf.decision_function([test_digit])

In [14]:
scores

array([[0.71707396, 0.71569927, 2.73651051, 6.10861713, 8.26670619,
        3.89526141, 0.70941008, 7.28008965, 5.08246049, 9.30839195]])

<h2>How Multiclass works under the Hood</h2>

In [15]:
index_for_class_3 = [i for i in range(len(y_train)) if y_train[i] == '3']

In [16]:
index_for_class_6 = [i for i in range(len(y_train)) if y_train[i] == '6']

In [17]:
train_set_for_3 = X_train[index_for_class_3]

In [18]:
test_set_for_3 = y_train[index_for_class_3]

In [19]:
train_set_for_6 = X_train[index_for_class_6]

In [20]:
test_set_for_6 = y_train[index_for_class_6]

In [42]:
train_set = np.concatenate([X_train[index_for_class_3], X_train[index_for_class_6]])

In [43]:
test_set = np.concatenate([y_train[index_for_class_3], y_train[index_for_class_6]])

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
train_data, test_data, train_target, test_target = train_test_split(train_set, test_set, test_size=0.3, random_state=42)

In [46]:
train_data.shape

(9811, 784)

In [47]:
train_target.shape

(9811,)

In [48]:
test_data.shape

(4206, 784)

In [49]:
test_target.shape

(4206,)

<h2>Creating a Binary Classifier which classifies only Two Classes</h2>

In [50]:
from sklearn.linear_model import SGDClassifier

In [51]:
sgd_clf = SGDClassifier(random_state=42)

In [52]:
sgd_clf.fit(train_data, train_target)

SGDClassifier(random_state=42)

In [53]:
test_digit1 = train_data[71]

In [54]:
test_digit2 = train_data[40]

In [55]:
sgd_clf.predict([test_digit1])

array(['6'], dtype='<U1')

In [56]:
train_target[71]

'6'

In [57]:
sgd_clf.predict([test_digit2])

array(['3'], dtype='<U1')

In [58]:
train_target[40]

'3'

In [59]:
model_score_for_3 = sgd_clf.decision_function([test_digit1])

In [60]:
model_score_for_6 = sgd_clf.decision_function([test_digit2])

In [61]:
model_score_for_3 # Came Positive hence this is a Class 3 Classifier

array([183233.51916172])

In [62]:
model_score_for_6

array([-1053770.66938726])